-- Insert Categories
INSERT INTO categories (id, name, slug, icon) VALUES (1, 'Imobiliare', 'imobiliare', '🏠') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (2, 'Auto', 'auto', '🚗') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (3, 'Electronice', 'electronice', '📱') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (4, 'Modă', 'moda', '👗') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (5, 'Servicii', 'servicii', '🔧') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (7, 'Auto Moto', 'auto-moto', '🚗') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (11, 'Casă & Grădină', 'casa-gradina', '🏡') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (12, 'Sport & Hobby', 'sport-hobby', '⚽') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (13, 'Animale', 'animale', '🐾') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (14, 'Locuri de Muncă', 'locuri-munca', '💼') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (15, 'Mama & Copilul', 'mama-copilul', '👶') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (16, 'Cărți & Muzică', 'carti-muzica', '📚') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, name, slug, icon) VALUES (17, 'Diverse', 'diverse', '📦') ON CONFLICT (id) DO NOTHING;

-- Insert Subcategories
INSERT INTO subcategories (id, category_id, name) VALUES (5, 1, 'Terenuri');
INSERT INTO subcategories (id, category_id, name) VALUES (4, 1, 'Case de închiriat');
INSERT INTO subcategories (id, category_id, name) VALUES (3, 1, 'Case de vânzare');
INSERT INTO subcategories (id, category_id, name) VALUES (6, 1, 'Garaje & Spații comerciale');
INSERT INTO subcategories (id, category_id, name) VALUES (2, 1, 'Apartamente de închiriat');
INSERT INTO subcategories (id, category_id, name) VALUES (1, 1, 'Apartamente de vânzare');
INSERT INTO subcategories (id, category_id, name) VALUES (7, 2, 'Autoturisme');
INSERT INTO subcategories (id, category_id, name) VALUES (8, 2, 'Motociclete & Scutere');
INSERT INTO subcategories (id, category_id, name) VALUES (9, 2, 'Piese auto');
INSERT INTO subcategories (id, category_id, name) VALUES (10, 2, 'Utilitare & Camioane');
INSERT INTO subcategories (id, category_id, name) VALUES (11, 2, 'Rulote & Autorulote');
INSERT INTO subcategories (id, category_id, name) VALUES (12, 2, 'Bărci & Ambarcațiuni');
INSERT INTO subcategories (id, category_id, name) VALUES (13, 3, 'Telefoane mobile');
INSERT INTO subcategories (id, category_id, name) VALUES (14, 3, 'Laptop & Desktop');
INSERT INTO subcategories (id, category_id, name) VALUES (15, 3, 'Tablete');
INSERT INTO subcategories (id, category_id, name) VALUES (16, 3, 'TV & Audio-Video');
INSERT INTO subcategories (id, category_id, name) VALUES (17, 3, 'Console & Gaming');
INSERT INTO subcategories (id, category_id, name) VALUES (18, 3, 'Camere foto & Video');
INSERT INTO subcategories (id, category_id, name) VALUES (19, 3, 'Accesorii electronice');
INSERT INTO subcategories (id, category_id, name) VALUES (24, 4, 'Ceasuri & Bijuterii');
INSERT INTO subcategories (id, category_id, name) VALUES (20, 4, 'Îmbrăcăminte femei');
INSERT INTO subcategories (id, category_id, name) VALUES (21, 4, 'Îmbrăcăminte bărbați');
INSERT INTO subcategories (id, category_id, name) VALUES (22, 4, 'Încălțăminte');
INSERT INTO subcategories (id, category_id, name) VALUES (23, 4, 'Genti & Accesorii');
INSERT INTO subcategories (id, category_id, name) VALUES (25, 5, 'Construcții & Renovări');
INSERT INTO subcategories (id, category_id, name) VALUES (26, 5, 'Reparații & Service');
INSERT INTO subcategories (id, category_id, name) VALUES (27, 5, 'Curățenie');
INSERT INTO subcategories (id, category_id, name) VALUES (28, 5, 'Transport & Mutări');
INSERT INTO subcategories (id, category_id, name) VALUES (29, 5, 'Evenimente & Petreceri');
INSERT INTO subcategories (id, category_id, name) VALUES (30, 5, 'Foto & Video');
INSERT INTO subcategories (id, category_id, name) VALUES (31, 5, 'IT & Web Design');
INSERT INTO subcategories (id, category_id, name) VALUES (37, 7, 'Echipamente sport');
INSERT INTO subcategories (id, category_id, name) VALUES (38, 7, 'Biciclete');
INSERT INTO subcategories (id, category_id, name) VALUES (39, 7, 'Sală & Fitness');
INSERT INTO subcategories (id, category_id, name) VALUES (40, 7, 'Camping & Drumeții');
INSERT INTO subcategories (id, category_id, name) VALUES (41, 7, 'Instrumente muzicale');
INSERT INTO subcategories (id, category_id, name) VALUES (42, 7, 'Colecții & Antichități');
INSERT INTO subcategories (id, category_id, name) VALUES (61, 11, 'Cărți');
INSERT INTO subcategories (id, category_id, name) VALUES (62, 11, 'Reviste');
INSERT INTO subcategories (id, category_id, name) VALUES (63, 11, 'CD & DVD');
INSERT INTO subcategories (id, category_id, name) VALUES (64, 11, 'Viniluri');
INSERT INTO subcategories (id, category_id, name) VALUES (101, 11, 'Electrocasnice');
INSERT INTO subcategories (id, category_id, name) VALUES (104, 11, 'Scule & Unelte');
INSERT INTO subcategories (id, category_id, name) VALUES (103, 11, 'Grădină & Terasă');
INSERT INTO subcategories (id, category_id, name) VALUES (102, 11, 'Decorațiuni');
INSERT INTO subcategories (id, category_id, name) VALUES (100, 11, 'Mobilier');
INSERT INTO subcategories (id, category_id, name) VALUES (106, 12, 'Biciclete');
INSERT INTO subcategories (id, category_id, name) VALUES (65, 12, 'Altele');
INSERT INTO subcategories (id, category_id, name) VALUES (66, 12, 'Echipamente industrie');
INSERT INTO subcategories (id, category_id, name) VALUES (67, 12, 'Schimburi');
INSERT INTO subcategories (id, category_id, name) VALUES (68, 12, 'Donații');
INSERT INTO subcategories (id, category_id, name) VALUES (105, 12, 'Echipamente sport');
INSERT INTO subcategories (id, category_id, name) VALUES (107, 12, 'Sală & Fitness');
INSERT INTO subcategories (id, category_id, name) VALUES (108, 12, 'Camping & Drumeții');
INSERT INTO subcategories (id, category_id, name) VALUES (109, 12, 'Instrumente muzicale');
INSERT INTO subcategories (id, category_id, name) VALUES (110, 12, 'Colecții & Antichități');
INSERT INTO subcategories (id, category_id, name) VALUES (111, 13, 'Câini');
INSERT INTO subcategories (id, category_id, name) VALUES (112, 13, 'Pisici');
INSERT INTO subcategories (id, category_id, name) VALUES (113, 13, 'Păsări');
INSERT INTO subcategories (id, category_id, name) VALUES (114, 13, 'Acvarii & Pești');
INSERT INTO subcategories (id, category_id, name) VALUES (115, 13, 'Alte animale');
INSERT INTO subcategories (id, category_id, name) VALUES (116, 13, 'Accesorii animale');
INSERT INTO subcategories (id, category_id, name) VALUES (117, 14, 'IT & Software');
INSERT INTO subcategories (id, category_id, name) VALUES (118, 14, 'Vânzări & Marketing');
INSERT INTO subcategories (id, category_id, name) VALUES (119, 14, 'Construcții');
INSERT INTO subcategories (id, category_id, name) VALUES (120, 14, 'Ospitalitate & Turism');
INSERT INTO subcategories (id, category_id, name) VALUES (121, 14, 'Educație & Formare');
INSERT INTO subcategories (id, category_id, name) VALUES (122, 14, 'Medical & Farmaceutic');
INSERT INTO subcategories (id, category_id, name) VALUES (123, 14, 'Alte joburi');
INSERT INTO subcategories (id, category_id, name) VALUES (124, 15, 'Îmbrăcăminte copii');
INSERT INTO subcategories (id, category_id, name) VALUES (125, 15, 'Jucării');
INSERT INTO subcategories (id, category_id, name) VALUES (126, 15, 'Cărucior & Scaune auto');
INSERT INTO subcategories (id, category_id, name) VALUES (127, 15, 'Articole bebeluși');
INSERT INTO subcategories (id, category_id, name) VALUES (128, 15, 'Mobilier copii');
INSERT INTO subcategories (id, category_id, name) VALUES (129, 16, 'Cărți');
INSERT INTO subcategories (id, category_id, name) VALUES (130, 16, 'Reviste');
INSERT INTO subcategories (id, category_id, name) VALUES (131, 16, 'CD & DVD');
INSERT INTO subcategories (id, category_id, name) VALUES (132, 16, 'Viniluri');
INSERT INTO subcategories (id, category_id, name) VALUES (133, 17, 'Altele');
INSERT INTO subcategories (id, category_id, name) VALUES (134, 17, 'Echipamente industrie');
INSERT INTO subcategories (id, category_id, name) VALUES (135, 17, 'Schimburi');
INSERT INTO subcategories (id, category_id, name) VALUES (136, 17, 'Donații');
