CREATE TABLE IF NOT EXISTS marketing_insights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  insight_type TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  source_agent TEXT,
  confidence_score FLOAT DEFAULT 0.0,
  actionable_steps TEXT[] DEFAULT '{}'::text[],
  status TEXT DEFAULT 'pending' -- pending, applied, archived
);

CREATE INDEX IF NOT EXISTS idx_marketing_insights_created_at ON marketing_insights(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_marketing_insights_type ON marketing_insights(insight_type);
